# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import time
from pathlib import Path
import cv2
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

import detect
from GUI import terminalWindow


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.path = 'TestImages/bus.jpg'
        self.savepath = 'runs'
        self.device = 'cpu'
        self.model = 'yolov5s.pt'
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Object detection")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.NoDrag)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 706, 22))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuDevice = QtWidgets.QMenu(self.menuSetting)
        self.menuDevice.setObjectName("menuDevice")
        self.menuModel = QtWidgets.QMenu(self.menuSetting)
        self.menuModel.setObjectName("menuModel")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_image = QtWidgets.QAction(MainWindow)
        self.actionOpen_image.setCheckable(False)
        self.actionOpen_image.setObjectName("actionOpen_image")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCPU = QtWidgets.QAction(MainWindow)
        self.actionCPU.setCheckable(True)
        self.actionCPU.setChecked(True)
        self.actionCPU.setObjectName("actionCPU")
        self.actionGPU = QtWidgets.QAction(MainWindow)
        self.actionGPU.setCheckable(True)
        self.actionGPU.setObjectName("actionGPU")
        self.actionOpen_folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_folder.setObjectName("actionOpen_folder")
        self.actionOpen_video = QtWidgets.QAction(MainWindow)
        self.actionOpen_video.setObjectName("actionOpen_video")
        self.actionTerminal = QtWidgets.QAction(MainWindow)
        self.actionTerminal.setObjectName("actionTerminal")
        self.actionyolov5s = QtWidgets.QAction(MainWindow)
        self.actionyolov5s.setCheckable(True)
        self.actionyolov5s.setChecked(True)
        self.actionyolov5s.setObjectName("actionyolov5s")
        self.actionyolov5m = QtWidgets.QAction(MainWindow)
        self.actionyolov5m.setCheckable(True)
        self.actionyolov5m.setObjectName("actionyolov5m")
        self.actionyolov5l = QtWidgets.QAction(MainWindow)
        self.actionyolov5l.setCheckable(True)
        self.actionyolov5l.setObjectName("actionyolov5l")
        self.actionyolov5x = QtWidgets.QAction(MainWindow)
        self.actionyolov5x.setCheckable(True)
        self.actionyolov5x.setObjectName("actionyolov5x")
        self.menuMain.addAction(self.actionOpen_image)
        self.menuMain.addAction(self.actionOpen_video)
        self.menuMain.addAction(self.actionOpen_folder)
        self.menuMain.addAction(self.actionSave)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionExit)
        self.menuDevice.addAction(self.actionCPU)
        self.menuDevice.addAction(self.actionGPU)
        self.menuModel.addAction(self.actionyolov5s)
        self.menuModel.addAction(self.actionyolov5m)
        self.menuModel.addAction(self.actionyolov5l)
        self.menuModel.addAction(self.actionyolov5x)
        self.menuSetting.addAction(self.menuModel.menuAction())
        self.menuSetting.addAction(self.menuDevice.menuAction())
        self.menuTools.addAction(self.actionTerminal)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.actionOpen_image.triggered.connect(self.open_img)
        self.actionOpen_video.triggered.connect(self.open_video)
        self.actionOpen_folder.triggered.connect(self.open_folder)
        self.pushButton.clicked.connect(self.run)
        self.pushButton_2.clicked.connect(self.change_save)
        self.actionCPU.triggered.connect(self.setCPU)
        self.actionGPU.triggered.connect(self.setGPU)
        self.actionyolov5s.triggered.connect(self.model_s)
        self.actionyolov5m.triggered.connect(self.model_m)
        self.actionyolov5l.triggered.connect(self.model_l)
        self.actionyolov5x.triggered.connect(self.model_x)
        self.terminal = terminalWindow.Ui_Dialog()
        # self.actionTerminal.triggered.connect(self.openTerminal)
        # self.actionTerminal.triggered.connect(self.terminal.show)
        self.actionTerminal.triggered.connect(self.show_terminal)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Object detection", "Object detection"))
        self.pushButton.setText(_translate("Object detection", "Run"))
        self.menuMain.setTitle(_translate("Object detection", "File"))
        self.menuSetting.setTitle(_translate("Object detection", "Setting"))
        self.menuDevice.setTitle(_translate("Object detection", "Device"))
        self.menuModel.setTitle(_translate("Object detection", "Model"))
        self.menuTools.setTitle(_translate("Object detection", "Tools"))
        self.actionOpen_image.setText(_translate("Object detection", "Open image"))
        self.actionSave.setText(_translate("Object detection", "Save"))
        self.actionExit.setText(_translate("Object detection", "Exit"))
        self.actionCPU.setText(_translate("Object detection", "CPU"))
        self.actionGPU.setText(_translate("Object detection", "GPU"))
        self.actionOpen_folder.setText(_translate("Object detection", "Open folder"))
        self.actionOpen_video.setText(_translate("Object detection", "Open video"))
        self.actionTerminal.setText(_translate("Object detection", "Terminal"))
        self.actionyolov5s.setText(_translate("Object detection", "yolov5s"))
        self.actionyolov5m.setText(_translate("Object detection", "yolov5m"))
        self.actionyolov5l.setText(_translate("Object detection", "yolov5l"))
        self.actionyolov5x.setText(_translate("Object detection", "yolov5x"))
        self.pushButton_2.setText(_translate("Object detection", "Change saving path"))

    def open_img(self):
        self.img_thread = Open_img(self)
        self.img_thread.start()

    def open_video(self):
        self.video_thread = Open_video(self)
        self.video_thread.start()

    def open_folder(self):
        self.folder_thread = Open_folder(self)
        self.folder_thread.start()

    def change_save(self):
        self.save_thread = Change_save(self)
        self.save_thread.start()

    def run(self):
        self.run_thread = Run(self)
        self.run_thread.start()

    def setCPU(self):
        self.cpu_thread = Set_cpu(self)
        self.cpu_thread.start()

    def setGPU(self):
        self.gpu_thread = Set_gpu(self)
        self.gpu_thread.start()

    def model_s(self):
        self.s_thread = Model_s(self)
        self.s_thread.start()

    def model_m(self):
        self.m_thread = Model_m(self)
        self.m_thread.start()

    def model_l(self):
        self.l_thread = Model_l(self)
        self.l_thread.start()

    def model_x(self):
        self.x_thread = Model_x(self)
        self.x_thread.start()

    def show_terminal(self):
        # self.terminal_thread = Show_terminal()
        # self.terminal_thread.start()
        self.terminal = terminalWindow.Ui_Dialog()
        self.terminal.show()
        # for i in range(1, 5):
        #     # text = sys.stdout
        #     # line = text.readline()
        #     self.terminal.textBrowser.setText(str(i))
        #     time.sleep(1)


class Run(QThread):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

    def run(self):
        # self.main_window.savepath = QFileDialog.getExistingDirectory(self.main_window,
        #                                                              'Choose a folder to save the result')
        # command = 'python3 detect.py --source ' + self.main_window.path + ' --project ' + self.main_window.savepath + \
        #           ' --device ' + self.main_window.device + ' --weights ' + self.main_window.model
        # command = 'detect.py --source ' + self.main_window.path + ' --project ' + self.main_window.savepath + \
        #           ' --device ' + self.main_window.device + ' --weights ' + self.main_window.model
        detect.run(window=self.main_window, source=self.main_window.path, weights=self.main_window.model,
                   device=self.main_window.device, project=self.main_window.savepath)
        # if (file_name[0] == ""):
        #     QMessageBox.information(self, "提示", self.tr("没有选择图片文件！"))
        p = Path(self.main_window.path)
        s = self.main_window.savepath + '/' + p.name
        if s.endswith(".jpg") or s.endswith(".png") or s.endswith(".jpeg"):
            img = cv2.imread(s)  # 读取图像
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # 转换图像通道
            img_x = img.shape[1]  # 获取图像大小
            img_y = img.shape[0]
            ratio = img_x / img_y
            window_x = self.main_window.graphicsView.width()
            window_y = self.main_window.graphicsView.height()
            if ratio * window_y <= window_x:
                x = int(ratio * (window_y - 20))
                y = window_y - 20
            else:
                x = window_x - 20
                y = int((window_x - 20) / ratio)
            print("resize")
            img = cv2.resize(img, (x, y))
            frame = QImage(img, x, y, QImage.Format_RGB888)
            pix = QPixmap.fromImage(frame)
            self.main_window.item = QGraphicsPixmapItem(pix)  # 创建像素图元
            # self.item.setScale(self.zoomscale)
            self.main_window.scene = QGraphicsScene()  # 创建场景
            self.main_window.scene.addItem(self.main_window.item)
            self.main_window.graphicsView.setScene(self.main_window.scene)  # 将场景添加至视图
        # TODO: if input is .mp4, show the first frame

        # TODO: if input is directory, show the first img or first frame of the first video


class Open_img(QThread):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

    def run(self):
        file_name = QFileDialog.getOpenFileName(self.main_window, 'Choose file', './', 'image(*.jpg , *.png)')
        image_path = file_name[0]
        # if (file_name[0] == ""):
        #     QMessageBox.information(self, "提示", self.tr("没有选择图片文件！"))
        print(image_path)
        self.main_window.path = image_path
        img = cv2.imread(image_path)  # 读取图像
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # 转换图像通道
        img_x = img.shape[1]  # 获取图像大小
        img_y = img.shape[0]
        ratio = img_x / img_y
        window_x = self.main_window.graphicsView.width()
        window_y = self.main_window.graphicsView.height()
        if ratio * window_y <= window_x:
            x = int(ratio * (window_y - 20))
            y = window_y - 20
        else:
            x = window_x - 20
            y = int((window_x - 20) / ratio)
        print("resize")
        img = cv2.resize(img, (x, y))
        frame = QImage(img, x, y, QImage.Format_RGB888)
        pix = QPixmap.fromImage(frame)
        self.main_window.item = QGraphicsPixmapItem(pix)  # 创建像素图元
        # self.item.setScale(self.zoomscale)
        self.main_window.scene = QGraphicsScene()  # 创建场景
        self.main_window.scene.addItem(self.main_window.item)
        self.main_window.graphicsView.setScene(self.main_window.scene)  # 将场景添加至视图


class Open_folder(QThread):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

    def run(self):
        self.main_window.path = QFileDialog.getExistingDirectory(self.main_window, 'Choose folder')
        # TODO: 检查文件夹内文件类型，只能接受视频和图片
        print(self.main_window.path)
        # TODO: show the first img or first frame of the first video


class Open_video(QThread):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

    def run(self):
        file_name = QFileDialog.getOpenFileName(self.main_window, 'Choose file', './', 'video(*.mp4)')
        self.main_window.path = file_name[0]
        # if (file_name[0] == ""):
        #     QMessageBox.information(self, "提示", self.tr("没有选择图片文件！"))
        print(self.main_window.path)
        # TODO: show the first frame

        # TODO: show each frame while running (optional)


class Set_gpu(QThread):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

    def run(self):
        self.main_window.device = '0'
        self.main_window.actionCPU.setChecked(False)


class Set_cpu(QThread):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

    def run(self):
        self.main_window.device = 'CPU'
        self.main_window.actionGPU.setChecked(False)


class Model_s(QThread):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

    def run(self):
        self.main_window.model = 'yolov5s.pt'
        self.main_window.actionyolov5m.setChecked(False)
        self.main_window.actionyolov5l.setChecked(False)
        self.main_window.actionyolov5x.setChecked(False)


class Model_m(QThread):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

    def run(self):
        self.main_window.model = 'yolov5m.pt'
        self.main_window.actionyolov5s.setChecked(False)
        self.main_window.actionyolov5l.setChecked(False)
        self.main_window.actionyolov5x.setChecked(False)


class Model_l(QThread):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

    def run(self):
        self.main_window.model = 'yolov5l.pt'
        self.main_window.actionyolov5m.setChecked(False)
        self.main_window.actionyolov5s.setChecked(False)
        self.main_window.actionyolov5x.setChecked(False)


class Model_x(QThread):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

    def run(self):
        self.main_window.model = 'yolov5x.pt'
        self.main_window.actionyolov5m.setChecked(False)
        self.main_window.actionyolov5l.setChecked(False)
        self.main_window.actionyolov5s.setChecked(False)


class Show_terminal(QThread):
    def __init__(self):
        super().__init__()

    def run(self):
        text = sys.stdout
        line = text.readline()
        self.terminal = terminalWindow.Ui_Dialog()
        self.terminal.show()


class Change_save(QThread):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

    def run(self):
        self.main_window.savepath = QFileDialog.getExistingDirectory(self.main_window, 'Choose save path')
